[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
remappings = [
]
fs_permissions = [{ access = "read-write", path = "./"}]
metadata="none"
solc = "0.8.22"
ffi = true

optimizer = true
optimizer_runs = 200
evm_version = 'shanghai'
bytecode_hash = 'none'


script_execution_protection = false

[profile.zksync.zksync]
fallback_oz = true
mode = "3"
zksolc="1.4.1"

[profile.linea]
evm_version = 'london'

[profile.linea-testnet]
evm_version = 'london'

[rpc_endpoints]
ethereum="${RPC_MAINNET}"
ethereum-testnet="${RPC_ETHEREUM_SEPOLIA}"
polygon="${RPC_POLYGON}"
polygon-testnet="${RPC_POLYGON_MUMBAI}"
arbitrum="${RPC_ARBITRUM}"
arbitrum_sepolia="${RPC_ARBITRUM_SEPOLIA}"
metis="${RPC_METIS}"
metis-testnet="${RPC_METIS_TESTNET}"
avalanche="${RPC_AVALANCHE}"
avalanche-testnet="${RPC_AVALANCHE_FUJI}"
optimism="${RPC_OPTIMISM}"
optimism-testnet="${RPC_OPTIMISM_TESTNET}"
fantom="${RPC_FANTOM}"
fantom-testnet="${RPC_FANTOM_TESTNET}"
binance="${RPC_BNB}"
binance-testnet="${RPC_BNB_TESTNET}"
base="${RPC_BASE}"
base-testnet="${RPC_BASE_TESTNET}"
gnosis="${RPC_GNOSIS}"
gnosis-testnet="${RPC_GNOSIS_TESTNET}"
zkevm="${RPC_ZKEVM}"
zkevm-testnet="${RPC_ZKEVM_TESTNET}"
scroll="${RPC_SCROLL}"
scroll-testnet="${RPC_SCROLL_TESTNET}"
celo="${RPC_CELO}"
celo-testnet="${RPC_CELO_ALFAJORES}"
zksync="${RPC_ZK_SYNC}"
zksync-testnet="${RPC_ZK_SYNC_TESTNET}"
linea="${RPC_LINEA}"
linea-testnet="${RPC_LINEA_SEPOLIA}"
sonic="${RPC_SONIC}"
sonic-testnet="${RPC_SONIC_TESTNET}"
mantle="${RPC_MANTLE}"
mantle-testnet="${RPC_MANTLE_TESTNET}"
ink="${RPC_INK}"
soneium="${RPC_SONEIUM}"
bob="${RPC_BOB}"
plasma="${RPC_PLASMA}"

[etherscan]
ethereum={key="${ETHERSCAN_API_KEY}", chain=1 }
ethereum_testnet={key="${ETHERSCAN_API_KEY}",chain=11155111}
optimism={key="${ETHERSCAN_API_KEY}",chain=10}
optimism-testnet={key="${ETHERSCAN_API_KEY}",chain=10}
avalanche={key="${ETHERSCAN_API_KEY}",chain=43114}
avalanche-testnet={key="${ETHERSCAN_API_KEY}",chain=43113}
polygon={key="${ETHERSCAN_API_KEY}",chain=137}
polygon-testnet={key="${ETHERSCAN_API_KEY}",chain=80001}
arbitrum={key="${ETHERSCAN_API_KEY}",chain=42161}
arbitrum_sepolia={key="${ETHERSCAN_API_KEY}",chain=42161}
metis={ key="any", chain=1088, url='https://andromeda-explorer.metis.io/' }
metis-testnet={ key="any", chain=599, url='https://goerli.explorer.metisdevops.link/' }
fantom={key="${ETHERSCAN_API_KEY}",chain=250}
fantom-testnet={key="${ETHERSCAN_API_KEY}",chain=250}
binance={key="${ETHERSCAN_API_KEY}",chain=56}
binance-testnet={key="${ETHERSCAN_API_KEY}",chain=97}
base={key="${ETHERSCAN_API_KEY}",chain=8453, url='https://developer-access-mainnet.base.org'}
base-testnet={key="${ETHERSCAN_API_KEY}",chain=8453, url='https://developer-access-mainnet.base.org'}
gnosis={key="${ETHERSCAN_API_KEY}",chain=100}
gnosis-testnet={key="${ETHERSCAN_API_KEY}",chain=10200, url='https://gnosis-chiado.blockscout.com/'}
zkevm={key="${ETHERSCAN_API_KEY}",chain=1101}
zkevm-testnet={key="${ETHERSCAN_API_KEY}",chain=1442}
scroll={key="${ETHERSCAN_API_KEY}", chain=534352, utl='https://api.scrollscan.com/api/'}
scroll-testnet={key="${ETHERSCAN_API_KEY}", chain=534351, url='https://api-sepolia.scrollscan.com/api/'}
celo={key="${ETHERSCAN_API_KEY}", chain=42220, utl='https://api.celoscan.io/api'}
celo-testnet={key="${ETHERSCAN_API_KEY}", chain=44787, url='https://api-alfajores.celoscan.io/api'}
zksync={key="${ETHERSCAN_API_KEY}", chain=324}
zksync-testnet={key="${ETHERSCAN_API_KEY}", chain=300, url='https://api-sepolia-era.zksync.network/api'}
linea={key="${ETHERSCAN_API_KEY}", chain=59144 }
linea-testnet={key="${ETHERSCAN_API_KEY}",chain=59141}
sonic={key="${ETHERSCAN_API_KEY}", chain=146, url='https://api.sonicscan.org/api'}
sonic-testnet={key="${ETHERSCAN_API_KEY}", chain=57054, url='https://api-testnet.sonicscan.org/api'}
mantle={key="${ETHERSCAN_API_KEY}", chain=5000, url='https://api.mantlescan.xyz/api'}
mantle-testnet={key="${ETHERSCAN_API_KEY}", chain=5003, url='https://explorer.testnet.mantle.xyz/api'}
ink={key="${ETHERSCAN_API_KEY}", chain=57073, url='https://api.routescan.io/v2/network/mainnet/evm/57073/etherscan'}
soneium={key="${ETHERSCAN_API_KEY}", chain=1868, url='https://soneium.blockscout.com/api/'}
bob={key="${ETHERSCAN_API_KEY}", chain=60808, url='https://explorer.gobob.xyz/api/'}

# See more config options https://github.com/gakonst/foundry/tree/master/config
[fuzz]
no_zksync_reserved_addresses = true
[invariant]
no_zksync_reserved_addresses = true
